project:
  type: website
  output-dir: docs

website:
  title: Nina Galanter
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    

editor: source

